import { prisma } from '@/lib/db'
import { getWeatherSnapshot } from '@/lib/weather'

export type DailyBriefRecord = {
  id: string
  date: Date
  tldr: string
  content: string
  audioUrl: string | null
  isRead: boolean
  isPinned: boolean
  createdAt: Date
  updatedAt: Date
}

function startOfDay(input: Date) {
  const d = new Date(input)
  d.setHours(0, 0, 0, 0)
  return d
}

function endOfDay(input: Date) {
  const d = startOfDay(input)
  d.setDate(d.getDate() + 1)
  return d
}

function parseDateOrToday(value?: string | null) {
  if (!value) return startOfDay(new Date())
  const parsed = new Date(value)
  if (Number.isNaN(parsed.getTime())) return startOfDay(new Date())
  return startOfDay(parsed)
}

export async function buildAutomatedBrief(date: Date) {
  const dayStart = startOfDay(date)
  const dayEnd = endOfDay(date)

  const [
    weather,
    dueToday,
    overdue,
    upcomingPlantings,
    unreadNotifications,
    unreadCount,
  ] = await Promise.all([
    getWeatherSnapshot(),
    prisma.gardenTask.findMany({
      where: { dueDate: { gte: dayStart, lt: dayEnd }, completed: false },
      orderBy: { dueDate: 'asc' },
      take: 8,
    }),
    prisma.gardenTask.findMany({
      where: { dueDate: { lt: dayStart }, completed: false },
      orderBy: { dueDate: 'asc' },
      take: 6,
    }),
    prisma.gardenPlanting.findMany({
      where: {
        OR: [
          { transplantDate: { gte: dayStart, lt: dayEnd } },
          { expectedHarvestDate: { gte: dayStart, lt: dayEnd } },
        ],
      },
      include: { plant: true },
      take: 6,
    }),
    prisma.notification.findMany({
      where: { isRead: false },
      orderBy: { createdAt: 'desc' },
      take: 6,
    }),
    prisma.notification.count({ where: { isRead: false } }),
  ])

  const tldrParts = [
    `${dueToday.length} garden tasks due today`,
    `${overdue.length} overdue tasks`,
    `${upcomingPlantings.length} planting milestones`,
    `${unreadCount} unread notifications`,
  ]

  const weatherLine = weather
    ? `Weather: ${Math.round(weather.current.temperatureC)}°C, ${weather.current.condition}. ${weather.recommendation.text}`
    : 'Weather: unavailable right now.'

  const contentLines = [
    `Daily briefing for ${dayStart.toLocaleDateString()}`,
    '',
    'TL;DR',
    `- ${tldrParts.join(' • ')}`,
    `- ${weatherLine}`,
    '',
    'Top priorities',
    ...overdue.slice(0, 3).map((task, i) => `${i + 1}. Overdue: ${task.title} (due ${task.dueDate.toLocaleDateString()})`),
    ...dueToday.slice(0, 3).map((task, i) => `${i + 1 + Math.min(3, overdue.length)}. Due today: ${task.title}`),
    '',
    'Upcoming garden milestones',
    ...(upcomingPlantings.length === 0
      ? ['- None for today']
      : upcomingPlantings.map((p) => {
          const transplant = p.transplantDate ? `transplant ${p.transplantDate.toLocaleDateString()}` : null
          const harvest = p.expectedHarvestDate ? `harvest ${p.expectedHarvestDate.toLocaleDateString()}` : null
          return `- ${p.plant.name}: ${[transplant, harvest].filter(Boolean).join(' • ') || 'status check'}`
        })),
    '',
    'Unread notifications',
    ...(unreadNotifications.length === 0
      ? ['- No unread notifications']
      : unreadNotifications.map((n) => `- ${n.title}: ${n.message}`)),
    '',
    'Automation notes',
    '- Morning refresh generated by Synapse Portal',
    '- Audio brief URL can be attached when Clark publishes the recording',
  ]

  return {
    tldr: tldrParts.join(' • '),
    content: contentLines.join('\n'),
    weatherSummary: weatherLine,
  }
}

export async function getOrCreateDailyBrief(dateInput?: Date) {
  const day = startOfDay(dateInput || new Date())

  const existing = await prisma.dailyBrief.findUnique({
    where: { date: day },
  })

  if (existing) return existing

  const generated = await buildAutomatedBrief(day)

  return prisma.dailyBrief.create({
    data: {
      date: day,
      tldr: generated.tldr,
      content: generated.content,
      audioUrl: null,
      isRead: false,
      isPinned: false,
    },
  })
}

export async function getBriefByDate(dateInput?: string | null) {
  const day = parseDateOrToday(dateInput)
  let brief = await prisma.dailyBrief.findUnique({ where: { date: day } })

  if (!brief) {
    brief = await getOrCreateDailyBrief(day)
  }

  return brief
}

export async function listBriefArchive(params?: {
  from?: string | null
  to?: string | null
  query?: string | null
  take?: number
}) {
  const from = params?.from ? startOfDay(new Date(params.from)) : undefined
  const to = params?.to ? endOfDay(new Date(params.to)) : undefined
  const take = params?.take ?? 60
  const query = params?.query?.trim()

  return prisma.dailyBrief.findMany({
    where: {
      ...(from || to
        ? {
            date: {
              ...(from ? { gte: from } : {}),
              ...(to ? { lt: to } : {}),
            },
          }
        : {}),
      ...(query
        ? {
            OR: [
              { tldr: { contains: query } },
              { content: { contains: query } },
            ],
          }
        : {}),
    },
    orderBy: [{ isPinned: 'desc' }, { date: 'desc' }],
    take,
  })
}

export async function searchBriefs(query: string, take = 40) {
  const q = query.trim()
  if (!q) return []

  return prisma.dailyBrief.findMany({
    where: {
      OR: [
        { tldr: { contains: q } },
        { content: { contains: q } },
      ],
    },
    orderBy: [{ isPinned: 'desc' }, { date: 'desc' }],
    take,
  })
}

export async function markBriefRead(id: string, isRead: boolean) {
  return prisma.dailyBrief.update({
    where: { id },
    data: { isRead },
  })
}

export async function pinBrief(id: string, isPinned: boolean) {
  return prisma.dailyBrief.update({
    where: { id },
    data: { isPinned },
  })
}
